storage:
  dbPath: "/var/mongodb/db"
net:
  bindIp : "127.0.0.1,192.168.103.100"
  port : 27000
setParameter:
   enableLocalhostAuthBypass: false
systemLog:
  destination: 'file'
  path: '/var/mongodb/db/mongod.log'
  logAppend: true
operationProfiling:
  mode: 'slowOp'
  slowOpThresholdMs: 50
